import Head from "next/head";

export default function Home() {
  return (
    <>
    
        <Head>
          <title>bocchi</title>
          <meta name="description" content="Generated by create next app" />
        </Head>
        <h1>main page</h1>

    </>
  );
}
