import Head from "next/head";
import Link from "next/link";
import styles from "../styles/Home.module.css";
// import connectMongo from "../utils/connectMongo";
// import Account from "../models/accountModel";

export default function Home({ accounts }) {
  return (
    <>
      <Head>
        <title>bocchi</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <div style={{ marginTop: "300px" }}>
        <h1>
          The elegant act of eating food <br /> without being disturbed by
          anyone
        </h1>
        <div className="d-grid gap-2 col-1 mx-auto">
          <Link href="/category" style={{ textDecoration: "none" }}>
            <button type="button" className={`${styles.startButton} btn btn-outline-dark btn-lg`}>
              Start
            </button>
          </Link>
        </div>
      </div>

      {/* {accounts.map((account)=>{
          return (
            <h1>{account.email}</h1>
          );
        })} */}
    </>
  );
}

// export const getServerSideProps = async () => {
//   try {
//     console.log('CONNECTING TO MONGO');
//     await connectMongo();
//     console.log('CONNECTED TO MONGO');

//     console.log('FETCHING DOCUMENTS');
//     const accounts = await Account.find();
//     console.log('FETCHED DOCUMENTS');

//     return {
//       props: {
//         accounts: JSON.parse(JSON.stringify(accounts)),
//       },
//     };
//   } catch (error) {
//     console.log(error);
//     return {
//       notFound: true,
//     };
//   }
// };
