import Head from "next/head";
import Link from "next/link";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <>
      <Head>
        <title>bocchi</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <div style={{ marginTop: "300px" }}>
        <h1>
          The elegant act of eating food <br /> without being disturbed by
          anyone
        </h1>
        <div className="d-grid gap-2 col-1 mx-auto">
          <Link href="/category" style={{ textDecoration: "none" }}>
            <button
              type="button"
              className={`${styles.startButton} btn btn-outline-dark btn-lg`}
            >
              Start
            </button>
          </Link>


          <Link href="/dbTest" style={{ textDecoration: "none" }}>
            <button
              type="button"
              className={`${styles.startButton} btn btn-outline-dark btn-lg`}
            >
              dbTest
            </button>
          </Link>
        </div>
      </div>
    </>
  );
}
