name: Acceptance-test

on:
  push:
    branches: [ "main" ]

jobs:
  acceptance-test:
    name: Acceptance-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Download artifact
        uses: actions/download-artifact@v3
        
      - name: Display structure of downloaded files
        run: ls -R
